config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :offers
  devise_for :users
  resources :users, only: %i[show edit update]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pincodes/set_pincode', to: 'pincodes#set_pincode', as: :set_pincode
  get 'pincodes/set_country', to: 'pincodes#set_country', as: :set_country
  get 'pincodes/set_state', to: 'pincodes#set_state', as: :set_state
  get 'pincodes/set_city', to: 'pincodes#set_city', as: :set_city
  get 'test', to: 'pincodes#test', as: :test
  post 'test_create', to: 'pincodes#test_create', as: :test_create

  get 'orders/:id/confirm', to: 'orders#confirm', as: :confirm
  resources :orders
  get '/checkouts', to: 'orders#checkouts', as: :checkouts

  resources :carts, except: %i[new show]
  resources :products, only: %i[index show], param: :slug

  resources :home, only: :create
  get '/contact', to: 'home#contact', as: :contact
  root 'home#index'
end

app/models/admin_user.rb
# frozen_string_literal: true

# :nodoc:
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
# frozen_string_literal: true

# :nodoc:
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/cart.rb
# frozen_string_literal: true

# :nodoc:
class Cart < ApplicationRecord
  # validation
  validates(
    :product_id,
    numericality: true,
    uniqueness: true,
    presence: true
  )
  validates(
    :user_id, :quantity,
    numericality: { greater_than: 0 },
    presence: true
  )

  # association
  belongs_to :user
  belongs_to :product
  belongs_to :product_color
  belongs_to :product_size

  # callback
  before_validation :set_default
  before_validation :set_total

  def set_default
    self.product_color_id = 1 if product_color_id.blank?
    self.product_size_id = 1 if product_size_id.blank?
    self.quantity = 1 if quantity.blank?
  end

  def set_total
    self.total = (product.mrp * quantity)
  end
end

app/models/category.rb
# frozen_string_literal: true

# :nodoc:
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/city.rb
# frozen_string_literal: true

# :nodoc:
class City < ApplicationRecord
  belongs_to :state
end

app/models/color.rb
# frozen_string_literal: true

# :nodoc:
class Color < ApplicationRecord
end

app/models/company.rb
# frozen_string_literal: true

# :nodoc:
class Company < ApplicationRecord
end

app/models/contact.rb
# frozen_string_literal: true

# :nodoc:
class Contact < ApplicationRecord
  # validation
  validates(
    :name,
    presence: { message: 'must be given please' },
    length: { minimum: 3, maximum: 50 }
  )
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :subject, presence: true, length: { minimum: 5, maximum: 100 }
  validates :message, presence: true, length: { minimum: 5, maximum: 500 }

  # callback
  after_commit :send_welcome_mail, on: :create

  def send_welcome_mail
    ContactMailer.welcome_email(self).deliver_now
  end
end

app/models/country.rb
# frozen_string_literal: true

# :nodoc:
class Country < ApplicationRecord
  has_many :states
end

app/models/location.rb
# frozen_string_literal: true

# :nodoc:
class Location < ApplicationRecord
  has_many :offer_locations, dependent: :destroy
end

app/models/offer.rb
# frozen_string_literal: true

# :nodoc:
class Offer < ApplicationRecord
  has_many :offer_locations, dependent: :destroy
  accepts_nested_attributes_for :offer_locations
end

app/models/order.rb
# frozen_string_literal: true

# :nodoc:
class Order < ApplicationRecord
  # # validations
  validates(
    :user_id, :payment_id,
    numericality: { greater_than: 0 },
    presence: true
  )

  validates(
    :payment_mode,
    inclusion: { in: %w[Cash Cheque Net-Banking],
                 message: 'only allows Cash, Cheque or Net Banking' }
  )

  # association
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products

  # callback
  after_commit :send_conformation_mail, on: :create
  after_update :order_status_mail, if: :saved_change_to_status?

  def send_conformation_mail
    OrderMailer.with(order_id: id).order_confirmation_send(self).deliver_now
  end

  def order_status_mail
    if status == 'Delivered'
      OrderMailer.with(order_id: id).order_status_delivered_send(self).deliver_now
    else
      OrderMailer.with(order_id: id).order_status_send(self).deliver_now
    end
  end
end

app/models/pincode.rb
# frozen_string_literal: true

# :nodoc:
class Pincode < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# :nodoc:
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :having_price_between, ->(minamount, maxamount) { where(price: minamount..maxamount) }

  has_one_attached :image
  belongs_to :category
  belongs_to :brand
  has_many :carts, dependent: :destroy
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  has_many :product_color, dependent: :destroy
  has_many :product_size, dependent: :destroy
end

app/models/product_size.rb
# frozen_string_literal: true

# :nodoc:
class ProductSize < ApplicationRecord
  belongs_to :size
  belongs_to :product
end

app/models/seo.rb
# frozen_string_literal: true

# :nodoc:
class Seo < ApplicationRecord
end

app/models/size.rb
# frozen_string_literal: true

# :nodoc:
class Size < ApplicationRecord
end

app/models/state.rb
# frozen_string_literal: true

# :nodoc:
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/tester.rb
# frozen_string_literal: true

# :nodoc:
class Tester < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# :nodoc:
class User < ApplicationRecord
  # Validation
  validates(
    :first_name, :last_name,
    presence: { message: 'must be given please' },
    length: { minimum: 3, maximum: 50 }
  )

  validates(
    :gender,
    inclusion: { in: %w[male female],
                 message: 'only allows Male or Female' }
  )
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Assocation
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# :nodoc:
class HomeController < ApplicationController
  before_action :set_paginate, only: :index

  def index
    @cart = Cart.new
    @categories = Category.where(active: true)
    @products = Product.page(@page).per(@per_page)
    @products = @products.where(category_id: params[:category_id]) if params[:category_id].present?
  end

  def contact
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        flash[:success] = 'Record created successfully.'
        format.html { redirect_to '/contact' }
      else
        format.html { render :contact }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end

  def tester_params
    params.require(:tester).permit(:country, :city, :state)
  end
end

app/views/theme_a/home/contact.html.haml
/ Page info
.page-top-info
  .container
    %h4 Contact
    .site-pagination
      %a{href: ""} Home
      \/
      %a{href: ""} Contact
/ Page info end
/ Contact section
%section.contact-section
  .container
    .row
      .col-lg-6.contact-info
        %h3 Get in touch
        %p= @company.address
        %p= @company.mobile
        %p= @company.email
        .contact-social
          - @profile.each do |profile|
            %a{href: "#{profile.url}"}
              %i{class: "fa fa-#{profile.provider}"}
        = form_with(url: home_index_path, model: @contact, class: 'contact-form', local: true) do |f|
          = f.label :name
          = f.text_field :name, placeholder: "Your Name", required: true
          - if @contact.errors.any?
            %p
              = @contact.errors.messages[:name].join(', ')
          = f.label :email
          = f.text_field :email, placeholder: "Your e-mail", required: true
          - if @contact.errors.any?
            %p
              = @contact.errors.messages[:email].join(', ')
          = f.label :subject
          = f.text_field :subject, placeholder: "Subject", required: true
          - if @contact.errors.any?
            %p
              = @contact.errors.messages[:subject].join(', ')
          = f.label :message    
          = f.text_area :message, placeholder: "Message", required: true
          - if @contact.errors.any?
            %p
              = @contact.errors.messages[:message].join(', ')
          %button.site-btn{type: 'submit'} SEND NOW
  .map
    %iframe{frameborder: "0", height: "400", marginheight: "0", marginwidth: "0", scrolling: "no", src: "https://maps.google.com/maps?width=100%&height=600&hl=en&coord=23.013228, 72.524532&q=1%20Softices Consultancy%20Pvt Ltd%2C%20Surat%2C%20Gujarat&ie=UTF8&t=&z=14&iwloc=B&output=embed", width: "100%"}
/ Contact section end
/ Related product section
%section.related-product-section.spad
  .container
    .section-title

app/views/theme_a/home/index.html.haml
/ Hero section
%section.hero-section
  .hero-slider.owl-carousel
    .hs-item.set-bg{"data-setbg": (asset_path "theme_a/img/bg-3.jpg")}
      .container
        .row
          .col-xl-6.col-lg-7.text-white
            %span New Arrivals
            %h2 New Product Collection
            %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus-pendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
            %a.site-btn.sb-white{href: "#{products_path}"} ADD TO CART
        .offer-card.text-white
          %span from
          %h2 $29
          %p SHOP NOW
    .hs-item.set-bg{"data-setbg": (asset_path "theme_a/img/bg-4.jpg")}
      .container
        .row
          .col-xl-6.col-lg-7.text-white
            %span New Arrivals
            %h2 HOT DEAL Up to 50% OFF
            %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus-pendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
            %a.site-btn.sb-white{href: "#{products_path}"} ADD TO CART
        .offer-card.text-white
          %span from
          %h2 $29
          %p SHOP NOW
  .container
    #snh-1.slide-num-holder
/ Hero section end
/ Features section
%section.features-section
  .container-fluid
    .row
      .col-md-4.p-0.feature
        .feature-inner
          .feature-icon
            / <img src="img/icons/1.png" width="30" alt="#">
            = image_tag "theme_a/img/icons/1.png", width: "30"
          %h2 Fast Secure Payments
      .col-md-4.p-0.feature
        .feature-inner
          .feature-icon
            / <img src="img/icons/2.png" width="30" alt="#">
            = image_tag "theme_a/img/icons/2.png", width: "30"
          %h2 Premium Products
      .col-md-4.p-0.feature
        .feature-inner
          .feature-icon
            / <img src="img/icons/3.png" width="30" alt="#">
            = image_tag "theme_a/img/icons/3.png", width: "30"
          %h2 Free  fast Delivery
/ Features section end
.banner-padding-bg
  .container
    .row{"data-gutter": "15"}
      .col-md-4
        .banner-2{style: "background-color:#83599A;"}
          %a.banner-link{href: "#"}
          .banner-caption-top-left
            %h5.banner-title Backpack Collection
            %p.banner-desc Don't Be Vague. Ask for Backpack .
            %p.banner-shop-now
              Shop Now
              %i.fa.fa-caret-right
          = image_tag "theme_a/img/bag.png", class: "banner-img", style: "bottom: -8px; right: -32px;", title: "Image Title"
      .col-md-4
        .banner-2{style: "background-color:#EF4D9C;"}
          %a.banner-link{href: "#"}
          .banner-caption-top-right
            %h5.banner-title Best 2015 Tablets
            %p.banner-desc Double the Pleasure, Double the Tablets.
            %p.banner-shop-now
              Shop Now
              %i.fa.fa-caret-right
          = image_tag "theme_a/img/tablets.png", class: "banner-img", style: "bottom: -22px; left: 0; width: 235px;", title: "Image Title"
      .col-md-4
        .banner-2{style: "background-color:#FEA92E;"}
          %a.banner-link{href: "#"}
          .banner-caption-bottom-left
            %h5.banner-title Top Glasses
            %p.banner-desc My Goodness, My Glasses!
            %p.banner-shop-now
              Shop Now
              %i.fa.fa-caret-right
          = image_tag "theme_a/img/glasses.png", class: "banner-img", style: "top: -4px; right: -15px; width: 220px;", title: "Image Title"
  / BLOCKS WRAP
%section{style: "background-color: #f8f8f8;"}
  .block-main.container
    .row
      .col-md-4.col-sm-4
        .block-content
          / <img src="img/1.jpg" class="img-responsive" alt=""/>
          = image_tag "theme_a/img/1.jpg", class: "img-responsive"
          .bs-text-down.text-center.hvr-outline-out
            Menswear
            %span Intimates Fall/Winter 2015
      .col-md-4.col-sm-4
        .block-content
          / <img src="img/5.jpg" class="img-responsive" alt=""/>
          = image_tag "theme_a/img/5.jpg", class: "img-responsive"
          .bs-text-center.text-center
            Accesories
            %span Get a new look with Smile Collection
      .col-md-4.col-sm-4
        .block-content
          / <img src="img/3.jpg" class="img-responsive" alt=""/>
          = image_tag "theme_a/img/3.jpg", class: "img-responsive"
          .bs-text-down.text-center
            Womenswear
            %span Smile Collection new arrivals
  .clearfix
/ letest product section
%section.product-filter-section{style: "margin-top: 15px;"}
  .container
    .section-title
      %h2{onclick: "this.style.backgroundColor='#009900';this.style.color='#FFFFFF';"}LATEST PRODUCTS
      %br
      .row
        .col-xl-3
        %ul.product-filter-menu
          %li
            %a{href: "#{root_path}"}All PRODUCTS
          - @categories.each do |category|
            %li
              %a{href: "#{root_path(category_id: category)}"}
                = category.name
    .row
      - @products.each do |product|
        .col-lg-3.col-sm-6
          .product-item
            .pi-pic
              - if product.available == "yes"
                %div
              - else
                .tag-new{style: "width: 96px;  line-height: 2;"} Out of Stock
              %a{href: "#{product_path(product)}"}
                = image_tag product.image
              -# = form_with(url: carts_path, model: @cart, local: true) do |form|
              -#   .field
              -#     = form.hidden_field :user_id, value: current_user.id if user_signed_in?
              -#   .field
              -#     = form.hidden_field :product_id, value: product.id
              -#   .field
              -#     = form.hidden_field :quantity
              -#   .field
              -#     = form.hidden_field :total, value: product.mrp
              -#   .field
              -#     = form.hidden_field :product_color_id
              -#   .field
              -#     = form.hidden_field :product_size_id
              -#   .pi-links
              -#     - unless user_signed_in? && Cart.where(user_id: current_user.id).pluck(:product_id).include?(product.id)
              -#       = form.submit 'Add to Cart', class: 'btn' if product.available == "yes"
              -#     - else
              -#       %a{href: "#{carts_path}", style: "background: none; width: 120px;"}Go To Cart
            .pi-text
              %h6= "$#{product.price}.00"
              %p= product.name
    .text-center.pt-5
      .cart-table{style: "background: white;"}
        .total-cost{style: "background: white;"}
          %h6{ style: "color: red;"}
            = paginate @products
      %h2= "No Product" if @products.blank?
      %br
      %button.site-btn.sb-line.sb-dark LOAD MORE
/ Product filter section end
/ Banner section
%section.banner-section
  .container
    .banner.set-bg{"data-setbg": (asset_path "theme_a/img/banner-bg.jpg")}
      .tag-new NEW
      %span New Arrivals
      %h2 STRIPED SHIRTS
      %a.site-btn{href: "#"} SHOP NOW
/ Banner section end
/ section
.section
  / container
  .container
    / row
    .row
      / banner
      .col-md-4.col-sm-6
        %a.banner.banner-1{href: "#"}
          = image_tag "theme_a/img/banner10.jpg"
          .banner-caption.text-center
            %h4.white-color.text-white NEW COLLECTION
      / /banner
      / banner
      .col-md-4.col-sm-6
        %a.banner.banner-1{href: "#"}
          = image_tag "theme_a/img/banner11.jpg"
          .banner-caption.text-center
            %h4.white-color.text-white NEW COLLECTION
      / /banner
      / banner
      .col-md-4.col-md-offset-0.col-sm-6.col-sm-offset-3
        %a.banner.banner-1{href: "#"}
          = image_tag "theme_a/img/banner12.jpg"
          .banner-caption.text-center
            %h4.white-color.text-white NEW COLLECTION
      / /banner
    / /row
  / /container
/ /section

app/views/theme_b/home/index.html.haml
/ Page Preloder
#preloder
  .loader
/ Hero Section Begin
%section.hero-section
  .hero-items.owl-carousel
    .single-hero-items.set-bg{"data-setbg": (asset_path "theme_b/hero-1.jpg")}
      .container
        .row
          .col-lg-5
            %span Bag,kids
            %h1 Black friday
            %p
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
              incididunt ut labore et dolore
            %a.primary-btn{href: "#{products_path}"} Shop Now
        .off-card
          %h2
            Sale
            %span 50%
    .single-hero-items.set-bg{"data-setbg": (asset_path "theme_b/hero-2.jpg")}
      .container
        .row
          .col-lg-5
            %span Bag,kids
            %h1 Black friday
            %p
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
              incididunt ut labore et dolore
            %a.primary-btn{href: "#{products_path}"} Shop Now
        .off-card
          %h2
            Sale
            %span 50%
/ Hero Section End
/ Banner Section Begin
.banner-section.spad
  .container-fluid
/ Banner Section End
/ Women Banner Section Begin
%section.women-banner.spad
  .container-fluid
    .row
      .col-lg-3
        .product-large.set-bg{"data-setbg": (asset_path "theme_b/products/women-large.jpg")}
          %h2 Women’s
          %a{href: "#"} Discover More
      .col-lg-8.offset-lg-1
        .filter-control{style: "font-size: 25px;"}
        .product-slider.owl-carousel
          - @products.where(category_id: Category.where(name: "Woman wear").pluck(:id)).each do |product|
            .product-item
              .pi-pic
                %a{href: "#{product_path(product.slug)}"}
                  = image_tag product.image, style: "height: 300px; width: 180px;"
                %div
                  - if product.available == "yes"
                    %p
                  - elsif product.available == "no"
                    .sale{style: "margin-bottom: 3px; margin-left: 2px;"} Out of Stock
                %ul
                  %li.quick-view
                    %a{href: "#{product_path(product.slug)}"} + Quick View
              .pi-text
                .catagory-name
                %a{href: "#"}
                  %h5= product.name
                .product-price
                  = "$#{product.price}.00"
                  %span $35.00
                .product-price
                  discount :
                  = "#{product.discount}%"
/ Women Banner Section End
/ Deal Of The Week Section Begin
%section.deal-of-week.set-bg.spad{"data-setbg": (asset_path "theme_b/time-bg.jpg")}
  .container
    .col-lg-6.text-center
      .section-title
        %h2 Deal Of The Week
        %p
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
          %br/
          do ipsum dolor sit amet,
          consectetur adipisicing elit
        .product-price
          $35.00
          %span / HanBag
      #countdown.countdown-timer
        .cd-item
          %span 56
          %p Days
        .cd-item
          %span 12
          %p Hrs
        .cd-item
          %span 40
          %p Mins
        .cd-item
          %span 52
          %p Secs
      %a.primary-btn{href: "#{products_path}"} Shop Now
/ Deal Of The Week Section End
/ Man Banner Section Begin
%section.man-banner.spad
  .container-fluid
    .row
      .col-lg-8
        .filter-control
        .product-slider.owl-carousel
          - @products.where(category_id: Category.where(name: "Man Wear").pluck(:id)).each do |product|
            .product-item
              .pi-pic
                %a{href: "#{product_path(product.slug)}"}
                  = image_tag product.image, style: "height: 300px; width: 180px;"
                %div
                - if product.available == "yes"
                  %p
                - elsif product.available == "no"
                  .sale{style: "margin-bottom: 3px; margin-left: 3px;"} Out of Stock
                %ul
                  %li.quick-view
                    %a{href: "#{product_path(product.slug)}"} + Quick View
              .pi-text
                .catagory-name
                %a{href: "#"}
                  %h5= product.name
                .product-price
                  = "$#{product.price}.00"
                  %span $35.00
                .product-price
                  discount :
                  = "#{product.discount}%"
      .col-lg-3.offset-lg-1
        .product-large.set-bg.m-large{"data-setbg": (asset_path "theme_b/products/man-large.jpg")}
          %h2 Men’s
          %a{href: "#"} Discover More
/ Man Banner Section End
/ Instagram Section Begin
.instagram-photo
  .insta-item.set-bg{"data-setbg": (asset_path "theme_b/insta-1.jpg")}
    .inside-text
      %i.fa.fa-instagram
      %h5
        %a{href: "#"} colorlib_Collection
  .insta-item.set-bg{"data-setbg": (asset_path "theme_b/insta-2.jpg")}
    .inside-text
      %i.fa.fa-instagram
      %h5
        %a{href: "#"} colorlib_Collection
  .insta-item.set-bg{"data-setbg": (asset_path "theme_b/insta-3.jpg")}
    .inside-text
      %i.fa.fa-instagram
      %h5
        %a{href: "#"} colorlib_Collection
  .insta-item.set-bg{"data-setbg": (asset_path "theme_b/insta-4.jpg")}
    .inside-text
      %i.fa.fa-instagram
      %h5
        %a{href: "#"} colorlib_Collection
  .insta-item.set-bg{"data-setbg": (asset_path "theme_b/insta-5.jpg")}
    .inside-text
      %i.fa.fa-instagram
      %h5
        %a{href: "#"} colorlib_Collection
  .insta-item.set-bg{"data-setbg": (asset_path "theme_b/insta-6.jpg")}
    .inside-text
      %i.fa.fa-instagram
      %h5
        %a{href: "#"} colorlib_Collection
/ Instagram Section End
/ Latest Blog Section Begin
%section.latest-blog.spad
  .container
    .row
      .col-lg-12
        .section-title
          %h2 From The Blog
    .row
      .col-lg-4.col-md-6
        .single-latest-blog
          = image_tag "theme_b/latest-1.jpg"
          .latest-text
            .tag-list
              .tag-item
                %i.fa.fa-calendar-o
                May 4,2019
              .tag-item
                %i.fa.fa-comment-o
                5
            %a{href: "#"}
              %h4 The Best Street Style From London Fashion Week
            %p Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
      .col-lg-4.col-md-6
        .single-latest-blog
          = image_tag "theme_b/latest-2.jpg"
          .latest-text
            .tag-list
              .tag-item
                %i.fa.fa-calendar-o
                May 4,2019
              .tag-item
                %i.fa.fa-comment-o
                5
            %a{href: "#"}
              %h4 Vogue's Ultimate Guide To Autumn/Winter 2019 Shoes
            %p Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
      .col-lg-4.col-md-6
        .single-latest-blog
          = image_tag "theme_b/latest-3.jpg"
          .latest-text
            .tag-list
              .tag-item
                %i.fa.fa-calendar-o
                May 4,2019
              .tag-item
                %i.fa.fa-comment-o
                5
            %a{href: "#"}
              %h4 How To Brighten Your Wardrobe With A Dash Of Lime
            %p Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
    .benefit-items
      .row
        .col-lg-4
          .single-benefit
            .sb-icon
              = image_tag "theme_b/icon-1.png"
            .sb-text
              %h6 Free Shipping
              %p For all order over 99$
        .col-lg-4
          .single-benefit
            .sb-icon
              = image_tag "theme_b/icon-2.png"
            .sb-text
              %h6 Delivery On Time
              %p If good have prolems
        .col-lg-4
          .single-benefit
            .sb-icon
              = image_tag "theme_b/icon-1.png"
            .sb-text
              %h6 Secure Payment
              %p 100% secure payment
/ Latest Blog Section End
/ Partner Logo Section Begin
.partner-logo
  .container
    .logo-carousel.owl-carousel
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-1.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-2.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-3.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-4.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-5.png"
/ Partner Logo Section End