config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :offers
  devise_for :users
  resources :users, only: %i[show edit update]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pincodes/set_pincode', to: 'pincodes#set_pincode', as: :set_pincode
  get 'pincodes/set_country', to: 'pincodes#set_country', as: :set_country
  get 'pincodes/set_state', to: 'pincodes#set_state', as: :set_state
  get 'pincodes/set_city', to: 'pincodes#set_city', as: :set_city
  get 'test', to: 'pincodes#test', as: :test
  post 'test_create', to: 'pincodes#test_create', as: :test_create

  get 'orders/:id/confirm', to: 'orders#confirm', as: :confirm
  resources :orders
  get '/checkouts', to: 'orders#checkouts', as: :checkouts

  resources :carts, except: %i[new show]
  resources :products, only: %i[index show], param: :slug

  resources :home, only: :create
  get '/contact', to: 'home#contact', as: :contact
  root 'home#index'
end

app/models/admin_user.rb
# frozen_string_literal: true

# :nodoc:
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
# frozen_string_literal: true

# :nodoc:
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/cart.rb
# frozen_string_literal: true

# :nodoc:
class Cart < ApplicationRecord
  # validation
  validates(
    :product_id,
    numericality: true,
    uniqueness: true,
    presence: true
  )
  validates(
    :user_id, :quantity,
    numericality: { greater_than: 0 },
    presence: true
  )

  # association
  belongs_to :user
  belongs_to :product
  belongs_to :product_color
  belongs_to :product_size

  # callback
  before_validation :set_default
  before_validation :set_total

  def set_default
    self.product_color_id = 1 if product_color_id.blank?
    self.product_size_id = 1 if product_size_id.blank?
    self.quantity = 1 if quantity.blank?
  end

  def set_total
    self.total = (product.mrp * quantity)
  end
end

app/models/category.rb
# frozen_string_literal: true

# :nodoc:
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/city.rb
# frozen_string_literal: true

# :nodoc:
class City < ApplicationRecord
  belongs_to :state
end

app/models/color.rb
# frozen_string_literal: true

# :nodoc:
class Color < ApplicationRecord
end

app/models/company.rb
# frozen_string_literal: true

# :nodoc:
class Company < ApplicationRecord
end

app/models/contact.rb
# frozen_string_literal: true

# :nodoc:
class Contact < ApplicationRecord
  # validation
  validates(
    :name,
    presence: { message: 'must be given please' },
    length: { minimum: 3, maximum: 50 }
  )
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :subject, presence: true, length: { minimum: 5, maximum: 100 }
  validates :message, presence: true, length: { minimum: 5, maximum: 500 }

  # callback
  after_commit :send_welcome_mail, on: :create

  def send_welcome_mail
    ContactMailer.welcome_email(self).deliver_now
  end
end

app/models/country.rb
# frozen_string_literal: true

# :nodoc:
class Country < ApplicationRecord
  has_many :states
end

app/models/location.rb
# frozen_string_literal: true

# :nodoc:
class Location < ApplicationRecord
  has_many :offer_locations, dependent: :destroy
end

app/models/offer.rb
# frozen_string_literal: true

# :nodoc:
class Offer < ApplicationRecord
  has_many :offer_locations, dependent: :destroy
  accepts_nested_attributes_for :offer_locations
end

app/models/order.rb
# frozen_string_literal: true

# :nodoc:
class Order < ApplicationRecord
  # # validations
  validates(
    :user_id, :payment_id,
    numericality: { greater_than: 0 },
    presence: true
  )

  validates(
    :payment_mode,
    inclusion: { in: %w[Cash Cheque Net-Banking],
                 message: 'only allows Cash, Cheque or Net Banking' }
  )

  # association
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products

  # callback
  after_commit :send_conformation_mail, on: :create
  after_update :order_status_mail, if: :saved_change_to_status?

  def send_conformation_mail
    OrderMailer.with(order_id: id).order_confirmation_send(self).deliver_now
  end

  def order_status_mail
    if status == 'Delivered'
      OrderMailer.with(order_id: id).order_status_delivered_send(self).deliver_now
    else
      OrderMailer.with(order_id: id).order_status_send(self).deliver_now
    end
  end
end

app/models/pincode.rb
# frozen_string_literal: true

# :nodoc:
class Pincode < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# :nodoc:
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :having_price_between, ->(minamount, maxamount) { where(price: minamount..maxamount) }

  has_one_attached :image
  belongs_to :category
  belongs_to :brand
  has_many :carts, dependent: :destroy
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  has_many :product_color, dependent: :destroy
  has_many :product_size, dependent: :destroy
end

app/models/product_size.rb
# frozen_string_literal: true

# :nodoc:
class ProductSize < ApplicationRecord
  belongs_to :size
  belongs_to :product
end

app/models/seo.rb
# frozen_string_literal: true

# :nodoc:
class Seo < ApplicationRecord
end

app/models/size.rb
# frozen_string_literal: true

# :nodoc:
class Size < ApplicationRecord
end

app/models/state.rb
# frozen_string_literal: true

# :nodoc:
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/tester.rb
# frozen_string_literal: true

# :nodoc:
class Tester < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# :nodoc:
class User < ApplicationRecord
  # Validation
  validates(
    :first_name, :last_name,
    presence: { message: 'must be given please' },
    length: { minimum: 3, maximum: 50 }
  )

  validates(
    :gender,
    inclusion: { in: %w[male female],
                 message: 'only allows Male or Female' }
  )
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Assocation
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/views/theme_a/_footer.html.haml
/ Footer section
%section.footer-section
  .container
    .footer-logo.text-center
      %a{href: "#{root_path}"}
        %h3.text-white Fasion
    .row
      .col-lg-3.col-sm-6
        .footer-widget.about-widget
          %h2 About
          %p Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.
          = image_tag 'theme_a/img/cards.png'
      .col-lg-3.col-sm-6
        .footer-widget.about-widget
          %h2 Questions
          %ul
            %li
              %a{href: "#"} About Us
            %li
              %a{href: "#"} Track Orders
            %li
              %a{href: "#"} Returns
            %li
              %a{href: "#"} Jobs
            %li
              %a{href: "#"} Shipping
            %li
              %a{href: "#"} Blog
          %ul
            %li
              %a{href: "#"} Partners
            %li
              %a{href: "#"} Bloggers
            %li
              %a{href: "#"} Support
            %li
              %a{href: "#"} Terms of Use
            %li
              %a{href: "#"} Press
      .col-lg-3.col-sm-6
        .footer-widget.about-widget
          %h2 Questions
          .fw-latest-post-widget
            .lp-item
              .lp-thumb.set-bg{"data-setbg": (asset_path "theme_a/img/blog-thumbs/1.jpg")}
              .lp-content
                %h6 what shoes to wear
                %span Oct 21, 2018
                %a.readmore{href: "#"} Read More
            .lp-item
              .lp-thumb.set-bg{"data-setbg": (asset_path "theme_a/img/blog-thumbs/2.jpg")}
              .lp-content
                %h6 trends this year
                %span Oct 21, 2018
                %a.readmore{href: "#"} Read More
      .col-lg-3.col-sm-6
        .footer-widget.contact-widget
          %h2 Questions
          .con-info
            %span C.
            %p= @company.name
          .con-info
            %span B.
            %p= @company.address
          .con-info
            %span T.
            %p= @company.mobile
          .con-info
            %span E.
            %p= @company.email
  .social-links-warp
    .container
      .social-links
        - @profile.each do |profile|
          %a{class: "#{profile.provider}", href: "#{profile.url}", target: "_blank"}
            %i{class: "fa fa-#{profile.provider}"}
            %span= profile.provider.capitalize
/ Footer section end

app/views/theme_a/_header.html.haml
%header.header-section
  .header-top
    .container
      .row
        .col-lg-2.text-center.text-lg-left
          / logo
          %a.site-logo{href: "#{root_path}"}
            %h2 FASION
        .col-xl-6.col-lg-5
          = form_tag products_path, method: 'get', class: 'header-search-form', style: 'background: #f0f0f0; border-radius: 50px;' do
            .row.address-inputs
              .col-md-11
                = text_field_tag :name, params[:name], placeholder: "Type Product Name"
              .col-md-1
                %button{type: 'submit', name: 'commit'}
                  %i.flaticon-search
        .col-xl-4.col-lg-5
          .user-panel
            .up-item
              - if user_signed_in?
                %ul.main-menu
                  %li
                    %i.flaticon-profile
                    %a= "#{current_user.first_name} #{current_user.last_name}"
                    %ul.sub-menu
                      %li
                        = link_to "Profile", current_user
                      %li
                        = link_to "Edit Profile", edit_user_registration_path
                      %li
                        = link_to "Sign Out", destroy_user_session_path, method: :delete
                      %li
                        %a{href: "#{orders_path}"} Orders
              - else
                %a{href: "#{new_user_session_path}"} Sign
                In or
                %a{href: "#{new_user_registration_path}"} Create Account
            .up-item
              .shopping-card
                %i.flaticon-bag
                - if @no_of_cart.blank?
                  %span= 0
                - else
                  %span= @no_of_cart
              %a{href: "#{carts_path}"} Shopping Cart
  %nav.main-navbar
    .container
      / menu
      %ul.main-menu
        %li
          %a{href: "#{root_path}"} Home
        %li
          %a{href: "#{products_path}"} Product
        %li
          %a{href: "#{contact_path}"} Contact

app/views/theme_b/_footer.html.haml
/ Footer Section Begin
%footer.footer-section
  .container
    .row
      .col-lg-3
        .footer-left
          .footer-logo
            %a{href: "#"}
              = image_tag "theme_b/footer-logo.png"
          %ul
            %li= @company.address
            %br
            %li= @company.mobile
            %li= @company.email
          .footer-social
            - @profile.each do |profile|
              %a{href: "#{profile.url}", target: "_blank"}
                %i{class: "fa fa-#{profile.provider}"}
      .col-lg-2.offset-lg-1
        .footer-widget
          %h5 Information
          %ul
            %li
              %a{href: "#"} About Us
            %li
              %a{href: "#"} Checkout
            %li
              %a{href: "#"} Contact
            %li
              %a{href: "#"} Serivius
      .col-lg-2
        .footer-widget
          %h5 My Account
          %ul
            %li
              %a{href: "#"} My Account
            %li
              %a{href: "#"} Contact
            %li
              %a{href: "#"} Shopping Cart
            %li
              %a{href: "#"} Shop
      .col-lg-4
        .newslatter-item
          %h5 Join Our Newsletter Now
          %p Get E-mail updates about our latest shop and special offers.
  .copyright-reserved
    .container
      .row
        .col-lg-12
          .copyright-text
            / Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
            Copyright ©
            :javascript
              document.write(new Date().getFullYear());
            All rights reserved | This template is made with
            %i.fa.fa-heart-o{"aria-hidden": "true"}
            by
            %a{href: "https://softices.com/", target: "_blank"} Softices
            / Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
          .payment-pic
            = image_tag "theme_b/payment-method.png"
/ Footer Section End

app/views/theme_b/_header.html.haml
%header.header-section
  .header-top
    .container
      .ht-left
        .mail-service
          %i.fa.fa-envelope
          = @company.email
        .phone-service
          %i.fa.fa-phone
          = @company.mobile
      .ht-right
        - if current_user
          %a.login-panel{href: " "}
            %i.fa.fa-user>
              = current_user.first_name
              = current_user.last_name
        - else
          %a.login-panel{style: "border-left: none;", href: "#{new_user_registration_path}"}
            Sign Up
          %a.login-panel{href: "#{new_user_session_path}"}
            %i.fa.fa-user>
            Sign In
        .top-social
          - @profile.each do |profile|
            %a.fa{class:"fa-#{profile.provider}", href:"#{profile.url}", target: '_blank'}
  .container
    .inner-header
      .row
        .col-lg-2.col-md-2
          .logo
            %a{href: "#{root_path}"}
              = image_tag "theme_b/logo.png"
        .col-lg-7.col-md-7
          = form_tag products_path, method: :get do
            .advanced-search
              .row
                -# .col-4
                -#   .input-group
                -#     = select_tag :category_id, options_for_select([['All', '']] + Category.pluck(:name, :id), selected: params[:category_id]), class: "form-control", style: "height: 48px;"
                .col-10
                  .input-group
                    = text_field_tag :name ,params[:name], placeholder: "Search product", style: "padding-top: 13px; padding-left: 65px;"
                .col-2
                  .input-group
                    %button{type: "submit"}
                      %i.fa.fa-search
        .col-lg-3.text-right.col-md-3
          %ul.nav-right
            %li.cart-icon
              %a{href: "#{carts_path}"}
                %i.fa.fa-shopping-bag
                - if @no_of_cart.blank?
                  %span= 0
                - else
                  %span= @no_of_cart
  .nav-item
    .container
      %nav.nav-menu.mobile-menu
        %ul
          %li{class: "#{current_class?(root_path)}"}
            = link_to "home", root_path
          %li{class: "#{current_class?(products_path)}"}
            = link_to "shop", products_path
          %li{class: "#{current_class?(contact_path)}"}
            = link_to "Contact", contact_path
          %li{class: ""}
            = link_to "Acount"
            %ul.dropdown
              - if defined?(Devise)
                - if user_signed_in?
                  %li{class: "#{current_class?(edit_user_registration_path)}"}
                    = link_to "Edit Profile", edit_user_registration_path
                  %li{class: "#{current_class?(destroy_user_session_path)}"}
                    = link_to "Logout", destroy_user_session_path, method: :delete
                  %li{class: "#{current_class?(orders_path)}"}
                    = link_to "All Orders", orders_path
                - else
                  %li{class: "#{current_class?(new_user_session_path)}"}
                    = link_to "Sign In", new_user_session_path
                  %li{class: "#{current_class?(new_user_registration_path)}"}
                    = link_to "Sign up", new_user_registration_path
      #mobile-menu-wrap
/ Header End