config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :offers
  devise_for :users
  resources :users, only: %i[show edit update]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pincodes/set_pincode', to: 'pincodes#set_pincode', as: :set_pincode
  get 'pincodes/set_country', to: 'pincodes#set_country', as: :set_country
  get 'pincodes/set_state', to: 'pincodes#set_state', as: :set_state
  get 'pincodes/set_city', to: 'pincodes#set_city', as: :set_city
  get 'test', to: 'pincodes#test', as: :test
  post 'test_create', to: 'pincodes#test_create', as: :test_create

  get 'orders/:id/confirm', to: 'orders#confirm', as: :confirm
  resources :orders
  get '/checkouts', to: 'orders#checkouts', as: :checkouts

  resources :carts, except: %i[new show]
  resources :products, only: %i[index show], param: :slug

  resources :home, only: :create
  get '/contact', to: 'home#contact', as: :contact
  root 'home#index'
end

app/models/admin_user.rb
# frozen_string_literal: true

# :nodoc:
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
# frozen_string_literal: true

# :nodoc:
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/cart.rb
# frozen_string_literal: true

# :nodoc:
class Cart < ApplicationRecord
  # validation
  validates(
    :product_id,
    numericality: true,
    uniqueness: true,
    presence: true
  )
  validates(
    :user_id, :quantity,
    numericality: { greater_than: 0 },
    presence: true
  )

  # association
  belongs_to :user
  belongs_to :product
  belongs_to :product_color
  belongs_to :product_size

  # callback
  before_validation :set_default
  before_validation :set_total

  def set_default
    self.product_color_id = 1 if product_color_id.blank?
    self.product_size_id = 1 if product_size_id.blank?
    self.quantity = 1 if quantity.blank?
  end

  def set_total
    self.total = (product.mrp * quantity)
  end
end

app/models/category.rb
# frozen_string_literal: true

# :nodoc:
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/city.rb
# frozen_string_literal: true

# :nodoc:
class City < ApplicationRecord
  belongs_to :state
end

app/models/color.rb
# frozen_string_literal: true

# :nodoc:
class Color < ApplicationRecord
end

app/models/company.rb
# frozen_string_literal: true

# :nodoc:
class Company < ApplicationRecord
end

app/models/contact.rb
# frozen_string_literal: true

# :nodoc:
class Contact < ApplicationRecord
  # validation
  validates(
    :name,
    presence: { message: 'must be given please' },
    length: { minimum: 3, maximum: 50 }
  )
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :subject, presence: true, length: { minimum: 5, maximum: 100 }
  validates :message, presence: true, length: { minimum: 5, maximum: 500 }

  # callback
  after_commit :send_welcome_mail, on: :create

  def send_welcome_mail
    ContactMailer.welcome_email(self).deliver_now
  end
end

app/models/country.rb
# frozen_string_literal: true

# :nodoc:
class Country < ApplicationRecord
  has_many :states
end

app/models/location.rb
# frozen_string_literal: true

# :nodoc:
class Location < ApplicationRecord
  has_many :offer_locations, dependent: :destroy
end

app/models/offer.rb
# frozen_string_literal: true

# :nodoc:
class Offer < ApplicationRecord
  has_many :offer_locations, dependent: :destroy
  accepts_nested_attributes_for :offer_locations
end

app/models/order.rb
# frozen_string_literal: true

# :nodoc:
class Order < ApplicationRecord
  # # validations
  validates(
    :user_id, :payment_id,
    numericality: { greater_than: 0 },
    presence: true
  )

  validates(
    :payment_mode,
    inclusion: { in: %w[Cash Cheque Net-Banking],
                 message: 'only allows Cash, Cheque or Net Banking' }
  )

  # association
  belongs_to :user
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products

  # callback
  after_commit :send_conformation_mail, on: :create
  after_update :order_status_mail, if: :saved_change_to_status?

  def send_conformation_mail
    OrderMailer.with(order_id: id).order_confirmation_send(self).deliver_now
  end

  def order_status_mail
    if status == 'Delivered'
      OrderMailer.with(order_id: id).order_status_delivered_send(self).deliver_now
    else
      OrderMailer.with(order_id: id).order_status_send(self).deliver_now
    end
  end
end

app/models/order_product.rb
# frozen_string_literal: true

# :nodoc:
class OrderProduct < ApplicationRecord
  # Association
  belongs_to :product
  belongs_to :order
  belongs_to :product_color
  belongs_to :product_size

  # callback
  after_initialize :set_default

  private

  def set_default
    self.discount = product.discount if discount.blank?
    self.discount_type = product.discount_type if discount_type.blank?
  end
end

app/models/pincode.rb
# frozen_string_literal: true

# :nodoc:
class Pincode < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# :nodoc:
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :having_price_between, ->(minamount, maxamount) { where(price: minamount..maxamount) }

  has_one_attached :image
  belongs_to :category
  belongs_to :brand
  has_many :carts, dependent: :destroy
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  has_many :product_color, dependent: :destroy
  has_many :product_size, dependent: :destroy
end

app/models/product_size.rb
# frozen_string_literal: true

# :nodoc:
class ProductSize < ApplicationRecord
  belongs_to :size
  belongs_to :product
end

app/models/seo.rb
# frozen_string_literal: true

# :nodoc:
class Seo < ApplicationRecord
end

app/models/size.rb
# frozen_string_literal: true

# :nodoc:
class Size < ApplicationRecord
end

app/models/state.rb
# frozen_string_literal: true

# :nodoc:
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/tester.rb
# frozen_string_literal: true

# :nodoc:
class Tester < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# :nodoc:
class User < ApplicationRecord
  # Validation
  validates(
    :first_name, :last_name,
    presence: { message: 'must be given please' },
    length: { minimum: 3, maximum: 50 }
  )

  validates(
    :gender,
    inclusion: { in: %w[male female],
                 message: 'only allows Male or Female' }
  )
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Assocation
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

# :nodoc:
class CartsController < ApplicationController
  before_action :set_cart, only: %i[edit update destroy]
  before_action :set_paginate, only: :index
  before_action :authenticate_user!

  def index
    @carts = current_user.carts.page(@page).per(@per_page)
  end

  def edit; end

  def create
    @product = Product.friendly.find_by(slug: params[:slug])
    @cart = Cart.new(cart_params)
    if @cart.save
      # format.html {}
      redirect_to carts_path
      flash[:success] = 'Cart was successfully created.'
    else
      # format.html { render template: 'products/show' }
      # format.json { render json: @cart.errors, status: :unprocessable_entity }
      flash[:alert] = @cart.errors
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to carts_path, notice: 'Cart was successfully updated.' }
        format.json { render :index, status: :ok, location: @cart }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_cart
    @cart = Cart.find_by(id: params[:id])
  end

  def cart_params
    params.require(
      :cart
    ).permit(
      :user_id, :product_id, :product_color_id, :product_size_id, :quantity, :total
    )
  end
end

app/views/theme_a/carts/edit.html.haml
%section.contact-section
  .container
    .row
      .col-lg-6.contact-info
        %h3 Editing Cart
        .cart-table
          .cart-table-warp
            %table{class: "form-group"}
              %thead
                %tr
                  %th.product-th Product
              %tbody
                %tr
                  %td.product-col
                    = image_tag @cart.product.image
                    .pc-title
                      %h4=  " Per #{@cart.product.name}"
                      %p= @cart.product.mrp
      .col-lg-6{style: "padding-top: 94px;"}
        = form_with(url: cart_path, model: @cart, local: true, class: "contact-form") do |form|
          .row
            .col-6
              .field
                = form.hidden_field :user_id
              .field
                = form.hidden_field :product_id
              .field
                .fw-color-choose{style: "border: none; margin-bottom: 26px; padding: 0;"}
                  %p{style: "float: left; margin-right: 30px; font-weight: 700;"} Color
                  - @cart.product.product_color.each do |product_color|
                    .cs-item
                      =  form.radio_button :product_color_id, product_color.id, checked: (product_color.id == @cart.product.product_color.first.id)
                      %label{style: "background-color: #{product_color.color.value}", for: "cart_product_color_id_#{product_color.id}"}
                      - if @cart.errors.any?
                        %p
                          = @cart.errors.messages[:product_color_id].join(', ')
              .field
                = form.label :quantity
                = form.number_field :quantity, required: true
                - if @cart.errors.any?
                  %p
                    = @cart.errors.messages[:quantity].join(', ')
            .col-6
              .field
                .fw-size-choose{style: "border: none; margin-bottom: 26px; padding: 0;"}
                  %p{style: "float: left; margin-right: 30px; font-weight: 700;"} Size
                  - @cart.product.product_size.each do |product_size|
                    .sc-item
                      =  form.radio_button :product_size_id, product_size.id, checked: (product_size.id == @cart.product.product_size.first.id)
                      %label{style: "width: 52px; border: 2px solid #414141", for: "cart_product_size_id_#{product_size.id}"}= product_size.size.name
                      - if @cart.errors.any?
                        %p
                          = @cart.errors.messages[:product_size_id].join(', ')
              .field
              .field
                = form.label :total
                = form.text_field :total, required: true
                - if @cart.errors.any?
                  %p
                    = @cart.errors.messages[:total].join(', ')
            .actions
              %button.site-btn{style: "margin-bottom: 45px;", type: 'submit'} Update
              %a.site-btn{style: "margin-bottom: 45px; color: white;", href: "#{carts_path}"} Back

app/views/theme_a/carts/index.html.haml
/ Page info
.page-top-info
  .container
    %h4 Your cart
    .site-pagination
      %a{href: "#{root_path}"} Home
      \/
      %a{href: "#{carts_path}"} Your cart
/ Page info end
%section
  .container
    .row
      %div{style: "margin-left: auto; margin-right: auto; padding-top: 12px;"}
        - unless @carts.present?
          = image_tag "theme_a/img/shoping_cart.jpg", style: "height: 172px; margin-left: auto; margin-right: auto; display: block; width: 201px;"
          %h3{style: "text-align: center; margin-top: 7px;"} Your cart is empty!
          %p{style: "text-align: center; margin-top: 7px;"} Add items for order.
          %a.site-btn.sb-dark{href: "#{products_path}"} Continue shopping
%section.cart-section.spad{style: "padding-top: 68px;"}
  .container
    .row
      .col-lg-12
        - if @carts.blank?
          %div{class: "cart-table-hide"}
        - else
          %div{class: "cart-table"}
            %h3 Your Cart
            .cart-table-warp
              %table{class: "form-group"}
                %thead
                  %tr
                    %th.product-th Product
                    %th.quy-th Quantity
                    %th.quy-th Color
                    %th.size-th Size
                    %th.total-th Price
                    %th.total-th{colspan: "2"} Action
                %tbody
                - @carts.each do |cart|
                  %tr
                    %td.product-col
                      = image_tag cart.product.image
                      .pc-title
                        %h4=  " Per #{cart.product.name}"
                        %p= cart.product.mrp
                    %td.size-col
                      %span= cart.quantity
                    %td.size-col
                      .fw-color-choose{style: "border: none; margin-bottom: -11px; padding: 0;"}
                        .cs-item
                          %label{style: "background-color: #{cart.product_color.color.value}"}
                    %td.size-col
                      %h4= cart.product_size.size.name
                    %td.total-col
                      %h4= best_in_place cart, :total
                    %td.total-col
                      = link_to " ",  edit_cart_path(cart), class: "flaticon-edit"
                    %td.total-col
                      = button_to "✖", cart_path(cart), method: :delete, class: "btn"
            .total-cost{style: "border-radius: 33px;"}
              %h6
                Total
                %span= "#{current_user.carts.pluck(:total).sum}"
            .total-cost{style: "background: white;"}
              %h6{ style: "color: red;"}
                = paginate @carts
        .col-lg-4.card-right
          - if @carts.present?
            %a.site-btn{href: "#{checkouts_path}"} Proceed to checkout

app/views/theme_b/carts/_cart.html.haml
.divTableCell= image_tag cart.product.image, style: "height: 150px; width: 152px;"
.divTableCell= cart.product.name
.divTableCell= cart.product.mrp
.divTableCell
  .fw-color-choose{style: "border: none; margin-bottom: -11px; padding: 0;"}
    .cs-item
      %label{style: "background-color: #{cart.product_color.color.value};"}
.divTableCell= cart.product_size.size.name
.divTableCell= cart.quantity
.divTableCell{id: "total#{cart.id}"}= cart.total
.divTableCell
  = link_to '', edit_cart_path(cart), remote: true, class: 'fa fa-pencil'
  = link_to '✖', cart, method: :delete, data: { confirm: 'Are you sure?' }

app/views/theme_b/carts/_cart_total.html.haml
.proceed-checkout{style: "padding-top: 18px;"}
  %ul
    %li.cart-total
      Total
      %span#finaltotal= "#{current_user.carts.pluck(:total).sum}"
  - if @carts.count == 0
    %a.proceed-btn{href: "#{products_path}"} Continue shopping
  - else
    %a.proceed-btn{href: "#{checkouts_path}"} PROCEED TO CHECK OUT

app/views/theme_b/carts/_inline_form.html.haml
= form_with model: cart, class: 'divTableRow', id: dom_id(cart, 'inline_form') do |form|
  .divTableCell
    = image_tag cart.product.image, style: "height: 150px; width: 152px;"
  .divTableCell= cart.product.name
  .divTableCell= cart.product.mrp
  .divTableCell
    = form.hidden_field :user_id
    = form.hidden_field :product_id
    = form.hidden_field :total
    .fw-color-choose{style: "border: none; margin-bottom: 26px; padding: 0;"}
      %p{style: "float: left;"}
      - @cart.product.product_color.each do |product_color|
        .cs-item
          =  form.radio_button :product_color_id, product_color.id, required: true
          %label{style: "background-color: #{product_color.color.value}", for: "cart_product_color_id_#{product_color.id}"}
  .divTableCell
    .product-details
      .pd-size-choose
        - @cart.product.product_size.each do |product_size|
          .sc-item
            = form.radio_button :product_size_id, product_size.id
            %label{class: "#{product_size.size.name}-size", for: "cart_product_size_id_#{product_size.id}", style: "width: 74px;"}= product_size.size.name
  .divTableCell
    = form.number_field :quantity, class: 'form-control'
  .divTableCell= cart.total
  .divTableCell
    = form.submit "Update", class: "primary-btn", style: "font-weight: 0px; padding: 0px; width: 109px;"

app/views/theme_b/carts/edit.js.haml
document.getElementById('#{dom_id(@cart)}').insertAdjacentHTML('afterend', "#{j render 'inline_form', cart: @cart}")
document.getElementById('#{dom_id(@cart)}').style.display = 'none'

app/views/theme_b/carts/index.html.haml
/ Page Preloder
#preloder
  .loader
/ Breadcrumb Section Begin
.breacrumb-section
  .container
    .row
      .col-lg-12
        .breadcrumb-text.product-more
          %a{href: "#{root_path}"}
            %i.fa.fa-home
            Home
          %a{href: "#{products_path}"} Shop
          %span Shopping Cart
/ Breadcrumb Section Begin
/ Shopping Cart Section Begin
%section.shopping-cart.spad
  .container
    .row
      .col-lg-12
        -# .cart-table
        -#   %table
        -#     %thead
        -#       %tr
        -#         %th Image
        -#         %th.p-name Product Name
        -#         %th Price
        -#         %th Color
        -#         %th Size
        -#         %th Quantity
        -#         %th Total
        -#         %th{colspan: "2"} Action
        -#     %tbody
        -#     - @carts.each do |cart|
        -#       %tr
        -#         %td.cart-pic.first-row
        -#           = image_tag cart.product.image, class: "img-fluid", style: "height: 150px; width: 152px;"
        -#         %td.cart-title.first-row
        -#           %h5= cart.product.name
        -#         %td.p-price.first-row= cart.product.mrp
        -#         %td.p-price.first-row
        -#           .fw-color-choose{style: "border: none; margin-bottom: -11px; padding: 0;"}
        -#             .cs-item
        -#               %label{style: "background-color: #{cart.product_color.color.value};"}
        -#         %td.p-price.first-row= cart.product_size.size.name
        -#         %td.qua-col.first-row
        -#           %h5= cart.quantity
        -#         %td.total-price.first-row= cart.total
        -#         %td.close-td.first-row
        -#           = link_to '', edit_cart_path(cart), class:"fa fa-pencil", style: "background: transparent; color: black;", method: :get, remote: true
        -#         %td.close-td.first-row
        -#           = button_to "✖", cart_path(cart), method: :delete, class: "btn"

        .divTable.paleBlueRows
          .divTableHeading
            .divTableRow
              .divTableHead Image
              .divTableHead Product Name
              .divTableHead Price
              .divTableHead Color
              .divTableHead Size
              .divTableHead Quantity
              .divTableHead Total
              .divTableHead Action
          .divTableBody
            - @carts.each do |cart|
              = content_tag :div, class: 'divTableRow', id: dom_id(cart) do
                .divTableCell= image_tag cart.product.image, style: "height: 150px; width: 152px;"
                .divTableCell= cart.product.name
                .divTableCell= cart.product.mrp
                .divTableCell
                  .fw-color-choose{style: "border: none; margin-bottom: -11px; padding: 0;"}
                    .cs-item
                      %label{style: "background-color: #{cart.product_color.color.value};"}
                .divTableCell= cart.product_size.size.name
                .divTableCell= cart.quantity
                .divTableCell{id: "total#{cart.id}"}= cart.total
                .divTableCell
                  = link_to '', edit_cart_path(cart), remote: true, class: 'fa fa-pencil'
                  = link_to '✖', cart, method: :delete, data: { confirm: 'Are you sure?' }


    .row
      .col-lg-4.offset-lg-4
        .proceed-checkout{style: "padding-top: 18px;"}
          %ul
            %li.cart-total
              Total
              %span#finaltotal= "#{current_user.carts.pluck(:total).sum}"
          - if @carts.count == 0
            %a.proceed-btn{href: "#{products_path}"} Continue shopping
          - else
            %a.proceed-btn{href: "#{checkouts_path}"} PROCEED TO CHECK OUT
    .row
      .col-lg-12
        .loading-more
          %i.fa
            %a{href: "#"}
              = paginate @carts
        %br

-# %table.head-table
-#   %tr
-#     %th{align: "right"} Class:
-#     %td 10
-#     %th{align: "right"} Div:
-#     %td A
-#   %tr
-#     %th{align: "right"} Teacher:
-#     %td Mr. krunal
-#     %th{align: "right"} Exam:
-#     %td Moke Test
-# %center
-#   %button{onclick: "add_row()", style: "margin:5px"} Add Row
-# %table#resulTable.result-table
-#   %tr
-#     %th{align: "center"} Roll No.
-#     %th{align: "center"} Name
-#     %th{align: "center"} English
-#     %th{align: "center"} Hindi
-#     %th{align: "center"} Math
-#     %th{align: "center"} Total
-#     %th{align: "center"} Persentage
-# %h1{align: "center"} Exam Summary
-# %table.summary-table
-#   %tr
-#     %th No. of Student
-#     %td#noOfStudent
-#   %tr
-#     %th Highest
-#     %td#highest
-#   %tr
-#     %th lowest
-#     %td#lowest
-#   %tr
-#     %th Avarege
-#     %td#average
-#   %tr
-#     %th Final total
-#     %td#finaltotal
/ Shopping Cart Section End
/ Partner Logo Section Begin
.partner-logo
  .container
    .logo-carousel.owl-carousel
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-1.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-2.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-3.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-4.png"
      .logo-item
        .tablecell-inner
          = image_tag "theme_b/logo-carousel/logo-5.png"
/ Partner Logo Section End

app/views/theme_b/carts/update.js.haml
document.getElementById('#{dom_id(@cart, 'inline_form')}').remove()
document.getElementById('#{dom_id(@cart)}').innerHTML = "#{j render @cart}"
document.getElementById('#{dom_id(@cart)}').style.display = 'table-row'
$('.proceed-checkout').html("#{j render(partial: 'cart_total')}");